---
  - name: installing and launching filebeat
    hosts: webservers
    become: yes
    tasks:
    - name: download filebeat deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

    - name: install filebeat deb
      command: sudo dpkg -i filebeat-7.4.0-amd64.deb

    - name: drop in filebeat.yml
      copy:
        src: ./filebeat-config.yml
        dest: /etc/filebeat/

    - name: enable and configure system module
      command: /usr/bin/filebeat modules enable system

    - name: setup filebeat
      command: /usr/bin/filebeat setup

    - name: start filebeat service
      command: service filebeat start
